# Generated by Django 5.2.6 on 2025-11-28 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace_name', models.CharField(max_length=200)),
                ('workplace_address', models.CharField(blank=True, max_length=255)),
                ('workplace_reg_no', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('daily_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('has_paid_weekly_holiday', models.BooleanField(default=True)),
                ('is_severance_eligible', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('calculation_type', models.CharField(max_length=50)),
                ('input_data_json', models.JSONField(blank=True, null=True)),
                ('total_annual_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('used_annual_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remaining_annual_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expected_base_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_overtime_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_total_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('detail_json', models.JSONField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('law_version_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='labor.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('time_in', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('break_minutes', models.IntegerField(default=0)),
                ('is_overtime', models.BooleanField(default=False)),
                ('is_night', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='labor.employee')),
            ],
            options={
                'ordering': ['-work_date'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
