# Generated by Django 5.2.6 on 2025-11-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_rate_last_year',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='작년 출근율 0~1', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_days_last_3m',
            field=models.IntegerField(blank=True, help_text='최근 3개월 총일수', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_wage_last_3m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='최근 3개월 총임금', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_days_per_week',
            field=models.IntegerField(blank=True, help_text='주 근로일수 (없으면 weekly_hours/daily_hours로 추정)', null=True),
        ),
    ]
